// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.14.0
// source: main_control.proto

package storagecontrol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StorageControlClient is the client API for StorageControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageControlClient interface {
	ReadStorageData(ctx context.Context, in *ReadStorageDataRequest, opts ...grpc.CallOption) (*ReadStorageDataResponse, error)
}

type storageControlClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageControlClient(cc grpc.ClientConnInterface) StorageControlClient {
	return &storageControlClient{cc}
}

func (c *storageControlClient) ReadStorageData(ctx context.Context, in *ReadStorageDataRequest, opts ...grpc.CallOption) (*ReadStorageDataResponse, error) {
	out := new(ReadStorageDataResponse)
	err := c.cc.Invoke(ctx, "/storagecontrol.StorageControl/ReadStorageData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageControlServer is the server API for StorageControl service.
// All implementations must embed UnimplementedStorageControlServer
// for forward compatibility
type StorageControlServer interface {
	ReadStorageData(context.Context, *ReadStorageDataRequest) (*ReadStorageDataResponse, error)
	mustEmbedUnimplementedStorageControlServer()
}

// UnimplementedStorageControlServer must be embedded to have forward compatible implementations.
type UnimplementedStorageControlServer struct {
}

func (UnimplementedStorageControlServer) ReadStorageData(context.Context, *ReadStorageDataRequest) (*ReadStorageDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadStorageData not implemented")
}
func (UnimplementedStorageControlServer) mustEmbedUnimplementedStorageControlServer() {}

// UnsafeStorageControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageControlServer will
// result in compilation errors.
type UnsafeStorageControlServer interface {
	mustEmbedUnimplementedStorageControlServer()
}

func RegisterStorageControlServer(s grpc.ServiceRegistrar, srv StorageControlServer) {
	s.RegisterService(&StorageControl_ServiceDesc, srv)
}

func _StorageControl_ReadStorageData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadStorageDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageControlServer).ReadStorageData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storagecontrol.StorageControl/ReadStorageData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageControlServer).ReadStorageData(ctx, req.(*ReadStorageDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageControl_ServiceDesc is the grpc.ServiceDesc for StorageControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storagecontrol.StorageControl",
	HandlerType: (*StorageControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadStorageData",
			Handler:    _StorageControl_ReadStorageData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "main_control.proto",
}
